DROP TABLE IF EXISTS PROCESSING;
CREATE TABLE PROCESSING (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  data varchar(200) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS PROCESSED;
CREATE TABLE PROCESSED (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  data varchar(200) NOT NULL,
  date DATE,
  sequence BIGINT(20),
  PRIMARY KEY (id)
);
